# Generated by Django 5.0.6 on 2024-07-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leyend',
            options={'ordering': ['-created'], 'verbose_name': 'leyenda', 'verbose_name_plural': 'leyendas'},
        ),
        migrations.AlterField(
            model_name='leyend',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='leyend',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='leyend',
            name='image',
            field=models.ImageField(upload_to='leyends', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='leyend',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='leyend',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
    ]
